export const CountryList = [
    'Austria',
    'Belgium',
    'Bulgaria',
    'Croatia',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Hungary',
    'Iceland',
    'Ireland',
    'Italy',
    'Luxembourg',
    'Malta',
    'Netherlands',
    'Norway',
    'Poland',
    'Portugal',
    'Romania',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Sweden',
    'Switzerland',
    'Türkiye',
    'Ukraine',
    'United Kingdom',
  ]

  export const wlRankData = [
    'NO WINS',
    '0 - 5 WINS',
    '5 - 10 WINS',
    '10 - 15 WINS',
    '15+ WINS',
  ]