import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#000',
    padding: 20,
  },
  tournamentTitle: {
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#D1CBD8',
    width: '75%',
  },
  tournamentDate: {
    fontFamily: 'Play-Regular',
    fontSize: 14,
    color: '#D1CBD8',
    width: '83%',
  },
  btnsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  ps5Btn: {
    paddingHorizontal: 6,
    backgroundColor: '#FFC1071F',
    paddingVertical: 5,
    borderRadius: 8,
  },
  ps5Text: {
    fontFamily: 'Play-Bold',
    color: '#FFC107',
    fontSize: 18,
  },
  efootBtn: {
    paddingHorizontal: 6,
    backgroundColor: '#1890FF1F',
    paddingVertical: 5,
    borderRadius: 8,
  },
  efootText: {
    fontFamily: 'Play-Bold',
    color: '#1890FF',
    fontSize: 18,
  },
  organizerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  organizerImage: {
    height: 24,
    width: 24,
    borderRadius: 50,
  },
  organizerInfo: {
    paddingVertical: 5,
  },
  organizedByText: {
    fontFamily: 'Play-Regular',
    fontSize: 12,
    color: '#D1CBD8',
  },
  organizerName: {
    fontFamily: 'Play-Bold',
    fontSize: 14,
    color: '#D1CBD8',
  },
  tournamentsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 30,
  },
  tournamentsTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  tournamentsTitle: {
    fontFamily: 'Play-Bold',
    fontSize: 20,
    color: '#D1CBD8',
  },
  showAllText: {
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#D1CBD8',
    textDecorationLine: 'underline',
  },
  tournamentCard: {
    width: '100%',
    backgroundColor: '#261D37',
    marginTop: 20,
    borderRadius: 8,
    flexDirection: 'row',
    padding: 20,
    gap: 20,
  },
  tournamentImage: {
    height: 210,
    width: 135,
    borderRadius: 8,
  },
  tournamentDetails: {
    flexDirection: 'column',
    gap: 6,
  },
  joinMatchButton: {
    height: 33,
    width: 117,
    backgroundColor: '#4A00E8',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  joinMatchButtonText: {
    fontFamily: 'Lato-Black',
    fontSize: 14,
    color: '#FFFFFF',
  },
  searchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 20,
  },
  searchInputContainer: {
    backgroundColor: '#261D37',
    borderRadius: 8,
    flexDirection: 'row',
    paddingLeft: 10,
    alignItems: 'center',
    gap: 5,
    paddingVertical: 1,
    width: '80%',
  },
  searchInput: {
    fontFamily: 'Play-Regular',
    fontSize: 18,
    color: '#D1CBD8',
    width: '88%',
  },
  filterIconContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#261D37',
    paddingVertical: 15,
    width: '15%',
  },
  container: {
    paddingHorizontal: 20,
  },
  header: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  headerText: {
    fontFamily: 'Play-Bold',
    fontSize: 20,
    color: '#D1CBD8',
  },
  deviceContainer: {
    paddingVertical: 40,
  },
  deviceText: {
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#D1CBD8',
  },
  deviceBox: {
    borderWidth: 1,
    borderColor: '#4A00E8',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
  deviceBoxText: {
    fontFamily: 'Play-Bold',
    fontSize: 14,
    color: '#D1CBD8',
  },
  availabilityText: {
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#D1CBD8',
  },
  availabilityBox: {
    borderWidth: 1,
    borderColor: '#4A00E8',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
  },
  availabilityBoxText: {
    fontFamily: 'Play-Bold',
    fontSize: 14,
    color: '#D1CBD8',
  },
  btnsView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 30,
  },
  cancelBtn: {
    borderWidth: 1,
    borderColor: '#D1CBD8',
    borderRadius: 8,
    width: '47%',
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#261D37',
  },
  cancelBtnText: {
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#D1CBD8',
  },
  applyBtn: {
    borderWidth: 1,
    borderColor: '#4A00E8',
    borderRadius: 8,
    width: '47%',
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4A00E8',
  },
  applyBtnText: {
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#D1CBD8',
  },
});
