import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#000',
    padding: 20,
  },
  upcomingGamesContainer: {
    paddingVertical: 10,
  },
  upcomingGamesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  upcomingGamesTitle: {
    fontFamily: 'Play-Bold',
    fontSize: 24,
    color: '#D1CBD8',
  },
  upcomingGamesImage: {
    width: '100%',
    height: 280,
    borderRadius: 10,
  },
  upcomingGameDetailsContainer: {
    backgroundColor: '#261D37',
    position: 'absolute',
    bottom: 9,
    opacity: 0.9,
    height: '32.5%',
    width: '100%',
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: '#3B3EFF',
  },
  upcomingGameDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 12,
    paddingHorizontal: 30,
  },
  gameInfo: {
    flexDirection: 'column',
    gap: 10,
  },
  gameTitle: {
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#D1CBD8',
  },
  gameAdmin: {
    fontFamily: 'Play-Regular',
    fontSize: 16,
    color: '#D1CBD8',
  },
  gameDate: {
    fontFamily: 'Play-Regular',
    fontSize: 14,
    color: '#D1CBD8',
  },
  gamesAvailableContainer: {
    paddingVertical: 30,
  },
  gamesAvailableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  gamesAvailableTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  gamesAvailableTitle: {
    fontFamily: 'Play-Bold',
    fontSize: 20,
    color: '#D1CBD8',
  },
  showAllText: {
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#D1CBD8',
    textDecorationLine: 'underline',
  },
  gameCard: {
    width: '100%',
    backgroundColor: '#261D37',
    marginTop: 20,
    height: 175,
    borderRadius: 8,
    flexDirection: 'row',
    padding: 20,
    gap: 20,
  },
  gameImage: {
    height: 135,
    width: 135,
    borderRadius: 8,
  },
  gameDetails: {
    flexDirection: 'column',
    gap: 7,
  },
  joinMatchButton: {
    height: 33,
    width: 117,
    backgroundColor: '#4A00E8',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  joinMatchButtonText: {
    fontFamily: 'Lato-Black',
    fontSize: 14,
    color: '#FFFFFF',
  },
  onlineUsersContainer: {
    paddingVertical: 10,
  },
  onlineUsersHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  onlineUsersTitle: {
    fontFamily: 'Play-Bold',
    fontSize: 20,
    color: '#D1CBD8',
  },
  searchContainer: {
    flexDirection: 'row',
    paddingTop: 15,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  searchInputContainer: {
    backgroundColor: '#261D37',
    borderRadius: 8,
    flexDirection: 'row',
    paddingLeft: 10,
    alignItems: 'center',
    gap: 5,
    paddingVertical: 1,
    width: '80%',
  },
  searchInput: {
    fontFamily: 'Play-Regular',
    fontSize: 18,
    color: '#D1CBD8',
    width: '88%',
  },
  filterIconContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#261D37',
    paddingVertical: 15,
    width: '15%',
  },
  userCard: {
    paddingVertical: 17,
    paddingHorizontal: 20,
    backgroundColor: '#261D37',
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  userCardDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  userProfileImage: {
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  userName: {
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#D1CBD8',
  },
  userStats: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tournamentContainer: {
    paddingHorizontal: 6,
    backgroundColor: '#FFC1071F',
    paddingVertical: 5,
    borderRadius: 8,
    gap: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  tournamentCount: {
    fontFamily: 'Play-Bold',
    color: '#FFC107',
    fontSize: 18,
  },
  badgeContainer: {
    paddingHorizontal: 6,
    backgroundColor: '#1890FF1F',
    paddingVertical: 5,
    borderRadius: 8,
    gap: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  badgeCount: {
    fontFamily: 'Play-Bold',
    color: '#1890FF',
    fontSize: 18,
  },
  container: {
    paddingHorizontal: 20,
  },
  header: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  headerText: {
    fontFamily: 'Play-Bold',
    fontSize: 20,
    color: '#D1CBD8',
  },
  winCategoryContainer: {
    paddingVertical: 40,
  },
  winCategoryText: {
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#D1CBD8',
  },
  winCategoryBox: {
    borderWidth: 1,
    borderColor: '#4A00E8',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
  winCategoryBoxText: {
    fontFamily: 'Play-Bold',
    fontSize: 14,
    color: '#D1CBD8',
  },
  availabilityText: {
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#D1CBD8',
  },
  availabilityBox: {
    borderWidth: 1,
    borderColor: '#4A00E8',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
  },
  availabilityBoxText: {
    fontFamily: 'Play-Bold',
    fontSize: 14,
    color: '#D1CBD8',
  },
  btnsView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 30,
  },
  cancelBtn: {
    borderWidth: 1,
    borderColor: '#D1CBD8',
    borderRadius: 8,
    width: '47%',
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#261D37',
  },
  cancelBtnText: {
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#D1CBD8',
  },
  applyBtn: {
    borderWidth: 1,
    borderColor: '#4A00E8',
    borderRadius: 8,
    width: '47%',
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4A00E8',
  },
  applyBtnText: {
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#D1CBD8',
  },
  tooltipContainer: {
    backgroundColor: '#A6C79B',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 8,
  },
  tooltipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  tooltipText:{
    fontFamily: 'Play-Bold',
    fontSize: 16,
    color: '#277929',
  }
});
